site_name: Pyletree
site_description: Generate directory tree diagrams from the command line and Python API.
site_url: https://davi-furtado.github.io/pyletree
repo_url: https://github.com/davi-furtado/pyletree
nav:
  - Home: index.md
  - Usage: usage.md
  - API: api.md
theme: material
