[build-system]
requires = ["uv_build>=0.11.29,<0.12.0"]
build-backend = "uv_build"

[project]
name = "pyletree"
version = "2.7.0"
description = "Generate directory tree diagrams from the command line"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Davi Reis Furtado" },
    { name = "Leodanis Pozo Ramos" }
]
requires-python = ">=3.8"
dependencies = [
    "pathspec",
]
[project.scripts]
pyletree = "pyletree.__main__:main"

[project.urls]
Homepage = "https://davi-furtado.github.io/pyletree"

[dependency-groups]
docs = [
    "mkdocs>=1.6.1",
    "mkdocs-dracula-theme>=1.0.7",
    "mkdocstrings[python]>=0.26.1",
]